# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: mysql12
  database: rubycad
  username: andre_isaque
  password: admin
  host: localhost/phpmyadmin/
  pool: 5
  timeout: 5000

